### ISSUE TITLE
Overwrite the model

### ISSUE THREAD

**Issue by ftrier** [nicolas-ivanov/debug_seq2seq#11]
https://github.com/nicolas-ivanov/debug_seq2seq/blob/eb2147f58b8cd608437571f7ad49891680dee792/lib/nn_model/model.py#L35

Here an uninitialized model is stored and then loaded, potentially overwriting already existing models.

**Comment by nicolas-ivanov** [comment]
@ftrier you are right, thank you for pointing this out. Fixed.
