### ISSUE TITLE
Upgrade to latest Seq2seq API

### ISSUE THREAD

**Issue by farizrahman4u** [nicolas-ivanov/debug_seq2seq#3]

**Comment by nicolas-ivanov** [comment]
Cool! Sure.

**Comment by nextdawn** [comment]
so if I have installed the debug_seq2seq framwork before, how can I upgrade it?

**Comment by nicolas-ivanov** [comment]
@nextdawn I believe you need to update the file `lib/nn_model/model.py` according to the changes introduced in [Fariz's repo](https://github.com/farizrahman4u/seq2seq). See his readme for the details.

I'll update debug_seq2seq repo tomorrow.

**Comment by journey0621** [comment]
We look forward to the updated version of debug_seq2seq.

**Comment by nicolas-ivanov** [comment]
Upgraded.
