### ISSUE TITLE
 I found a small bug

### ISSUE THREAD

**Issue by vangorik** [nicolas-ivanov/debug_seq2seq#7]
File: lib/nn_model/train.py
Line: 68
`def save_model(nn_model):`
`    #model_full_path = os.path.join(DATA_PATH, 'nn_models', NN_MODEL_PATH)`
`    nn_model.save_weights(NN_MODEL_PATH, overwrite=True)`

**Comment by liveabstract** [comment]
@vangorik  : nn_models and nn_model, is that what you are saying?

Also, after fixing the issue, was there any change in the quality of results?

**Comment by vangorik** [comment]
before fix python reported error because:

If i set in line 5:
DATA_PATH = './test'

config.py line: 53
NN_MODEL_PATH = os.path.join(DATA_PATH, 'nn_models', NN_MODEL_NAME)
###NN_MODEL_PATH = './test/nn_models/'+NN_MODEL_NAME

and in lib/nn_model/train.py:
model_full_path = os.path.join(DATA_PATH, 'nn_models', NN_MODEL_PATH)
### model_full_path = 
'./test/nn_models/./test/nn_models/'+NN_MODEL_NAME   <<----- FAIL and 
save_weights dont save nn_model
nn_model.save_weights(model_full_path, overwrite=True)

Sorry about my poor English ;)


Dňa 3. 3. 2016 o 7:10 liveabstract napísal(a):

**Comment by vangorik** [comment]
ok i create pull request and corect others bugs :)

**Comment by nicolas-ivanov** [comment]
@vangorik thank you, I'm gonna take a look at it now
